services:
  - type: web
    name: email-scraper
    env: docker
    buildCommand: |
      docker build -t email-scraper .
    startCommand: docker run -p $PORT:$PORT -e PORT=$PORT email-scraper
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8080